basePath: /api/alpha
definitions:
  model.Login:
    properties:
      user_id:
        type: string
    required:
    - user_id
    type: object
  model.OrderProduct:
    properties:
      code:
        type: string
      currency:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      qty:
        type: integer
    required:
    - currency
    - id
    - price
    - qty
    type: object
  model.Pin:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  model.Store:
    properties:
      address:
        type: string
      code:
        type: string
      name:
        type: string
      owner:
        type: string
    required:
    - address
    - code
    - name
    type: object
  model.StoreOrder:
    properties:
      currency:
        type: string
      date:
        type: string
      payment_mode:
        type: string
      payment_no:
        type: string
      products:
        items:
          $ref: '#/definitions/model.OrderProduct'
        type: array
      recipe_no:
        type: string
      rounding:
        type: number
      status:
        type: string
      store:
        type: string
      subtotal:
        type: number
      tax_amount:
        type: number
      tax_percent:
        type: number
      teller:
        type: string
      time:
        type: string
      total:
        type: number
    required:
    - currency
    - date
    - products
    - status
    - store
    - teller
    - time
    - total
    type: object
  model.StoreProduct:
    properties:
      barcode:
        type: string
      buy_price:
        type: number
      category:
        type: string
      code:
        type: string
      currency:
        type: string
      id:
        type: string
      name:
        type: string
      qty:
        type: integer
      sell_price:
        type: number
      store:
        type: string
      unit:
        type: string
    required:
    - barcode
    - category
    - code
    - currency
    - name
    - sell_price
    - store
    - unit
    type: object
  model.Token:
    properties:
      token:
        type: string
      user_id:
        type: string
    required:
    - token
    - user_id
    type: object
host: aliracommerce.herokuapp.com
info:
  contact:
    email: hello@alira.com
    name: Alira Support
    url: https://www.commerce.alira.com/support
  description: Documentation of Alira commerce provides capability to manage customer
    store, inventory and sales order
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  termsOfService: https://commerce.alira.com/terms/
  title: Alira Commerce API
  version: alpha
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Handler user authentication
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            {"user_id": "UserID", "use_pin": "UsePin", "purpose": "Purpose"}}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Log in user
      tags:
      - Authentication
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Handler log out authenticated user
      parameters:
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Log out authenticated user
      tags:
      - Authentication
  /auth/token:
    post:
      consumes:
      - application/json
      description: Authentication token verification handler
      parameters:
      - description: Authentication Token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/model.Token'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Verify token
      tags:
      - Authentication
  /category:
    get:
      consumes:
      - application/json
      description: List of product category based on customer
      parameters:
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: List of Store
      tags:
      - Product
  /order:
    post:
      consumes:
      - application/json
      description: Create order by store
      parameters:
      - description: Store order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/model.StoreOrder'
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Create order
      tags:
      - Sales Order
  /order/{id}:
    get:
      consumes:
      - application/json
      description: Detail of order based on id or reference number provided
      parameters:
      - description: order id or reference number
        in: path
        name: id
        required: true
        type: string
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Order detail
      tags:
      - Sales Order
  /order/search:
    post:
      consumes:
      - application/json
      description: Find order based on customer or store
      parameters:
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Find orders
      tags:
      - Sales Order
  /product:
    post:
      consumes:
      - application/json
      description: Create new product based on customer and or store
      parameters:
      - description: Store product
        in: body
        name: store
        required: true
        schema:
          $ref: '#/definitions/model.StoreProduct'
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Create new product
      tags:
      - Product
  /product/{id}:
    get:
      consumes:
      - application/json
      description: Detail of product based on id provided
      parameters:
      - description: product id or barcode
        in: path
        name: id
        required: true
        type: string
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Product information
      tags:
      - Product
  /store:
    get:
      consumes:
      - application/json
      description: List of store based on customer
      parameters:
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: List of Store
      tags:
      - Store
    post:
      consumes:
      - application/json
      description: Create new store with
      parameters:
      - description: Store info
        in: body
        name: store
        required: true
        schema:
          $ref: '#/definitions/model.Store'
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Create new store
      tags:
      - Store
  /store/{id}:
    get:
      consumes:
      - application/json
      description: Detail of store based on id provided
      parameters:
      - description: store id
        in: path
        name: id
        required: true
        type: string
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Store information
      tags:
      - Store
  /store/search:
    post:
      consumes:
      - application/json
      description: Find store based on parameter
      parameters:
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Search Store
      tags:
      - Store
  /user/pin:
    post:
      consumes:
      - application/json
      description: Update authenticated user pin
      parameters:
      - description: User pin
        in: body
        name: pin
        required: true
        schema:
          $ref: '#/definitions/model.Pin'
      - description: Bearer [accessing token]
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "status": "OK", "message": "Success", "data":
            "data"}'
          schema:
            type: string
        "400":
          description: '{"code": 400, "status": "Bad request", "error": "Error"}'
          schema:
            type: string
      summary: Change user pin
      tags:
      - User
swagger: "2.0"
